version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/html/


hooks:
   Afterinstall:
         - location: script/Install.sh
           timeout: 100
           runas: root
   ApplicationStop:
         - location: script/stop_script.sh
           timeout: 100
           runas: root

   ApplicationStart:
         - location: script/start_script.sh
           timeout: 100
           runas: root 
